name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: dotnet build App/App.csproj --no-restore

    - name: Run App in new console
      shell: pwsh
      run: |
        Start-Process powershell -ArgumentList '-NoExit', '-Command', 'dotnet run --project App'
